### ISSUE TITLE
Support for env vars

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/boring-serverless#7]
Hamr should be able to inject env vars into apps.

For now, it should
- Take env vars from `config.yml` -> `env`
- Inject it into environ before running the app

`config.yml` could look like:
```yaml
env:
    smtp_hostname: localhost
    smtp_port: 8025
    smtp_username: user
    smtp_password: topsecret
```

The keys should be uppercased before setting, as a convention.
